# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867369bb92d52e040766b1500bd06f48380f2812b1a114fa02c35d717917cb1b1e377fb6a4eb39d920e8e2179d0ffd43ce0b6c59b6c52d0988400c53e1245bf3

test:
  secret_key_base: 1fba014f283731210ed431942aece5bf80cd11d2051ff5d5d1eae6e4b43909d82a6456e1538dfe9b1dc3cf1d79f37edc480211e8ac58659e018754eb1a5a3c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
